### ISSUE TITLE
你好，关于fastjson2.x热重载

### ISSUE THREAD

**Issue by sa-yuki** [sujingkpo/idea-plugin-jrebel-fastjson#1]
fastjson2.x的SerializeConfig.isAsmEnable方法没有了，这个方法现在在ParserConfig.isAsmEnable，使用插件热重载时会抛出异常 JRebel plugin while handling a class reload event: java.lang.NoSuchMethodError: com.alibaba.fastjson.serializer.SerializeConfig.isAsmEnable()Z

**Comment by sujingkpo** [comment]
已上传新的版本, 稍后请验证, 或者release下载自行更新试用一下
